@startuml
!theme plain
skinparam linetype ortho
skinparam DefaultFontName sans-serif
skinparam DefaultFontSize 16

together {
    Class "<b>DAPT Script</b>" [[#dapt-script]] {
        Script Type [[[#script-type]]]
        Primary Language [[[#primary-language]]]
    }

    Class "<b>Script Event</b>" [[#script-event]] {
        Script Event Identifier [[[#dfn-script-event-identifier]]]
        Begin [[[#dfn-begin]]]
        End [[[#dfn-end]]]
        {field} (optional) Script Event Type [[[#dfn-script-event-type]]]
        {field} (optional) Script Event Description [[[#dfn-script-event-description]]]
        {field} (optional) On Screen [[[#on-screen]]]
    }

    Class "<b>Text</b>" [[#text]] {
        Text content [[[#dfn-text]]]
        Text Language Source [[[#text-language-source]]]
        {field} (optional) Language
    }
}

together {
    Class "<b>Character</b>" [[#character]] {
        Character Identifier [[[#dfn-character-identifier]]]
        Name [[[#dfn-character-name]]]
        {field} (optional) Talent Name [[[#dfn-character-talent-name]]]
    }

    Class "<b>Style</b>" {
        Style Identifier
        {field} (optional) Character Identifier [[[#dfn-character-identifier]]]
        Style Attributes
    }
}

"<b>DAPT Script</b>" "0" *-- "many" "<b>Script Event</b>" : contains
"<b>DAPT Script</b>" "0" *-- "many" "<b>Character</b>" : contains
"<b>DAPT Script</b>" "0" *-- "many" "<b>Style</b>" : contains
"<b>Character</b>" "0" <.. "many" "<b>Style</b>" [[#dfn-character-style]] : Character Style
"<b>Script Event</b>" "0" ..> "many" "<b>Style</b>" [[#dfn-character-style]] : Character Style
"<b>Text</b>" "0" ..> "many" "<b>Style</b>" [[#dfn-character-style]] : Character Style
"<b>Text</b>" "0" ..> "many" "<b>Style</b>" : Other Style
"<b>Script Event</b>" "0" *-- "many" "<b>Text</b>" : contains
"<b>Script Event</b>" "0" ..> "many" "<b>Character</b>"

hide empty members
hide circle
@enduml