@startuml
!theme plain
!pragma ratio 1.3
skinparam linetype ortho
skinparam DefaultFontName sans-serif
skinparam DefaultFontSize 16
skinparam ArrowFontSize 14
skinparam ArrowMessageAlignment direction
skinparam Padding 4
skinparam Nodesep 2
skinparam Ranksep 0

together {
    Class DAPTScript as "**DAPT Script**" [[#dapt-script]] {
        Script Type [[[#script-type]]]
        Primary Language [[[#primary-language]]]
    }

    Class ScriptEvent as "**Script Event**" [[#script-event]] {
        Script Event Identifier [[[#dfn-script-event-identifier]]]
        Begin [[[#dfn-begin]]]
        End [[[#dfn-end]]]
        {field} (optional) Script Event Type [[[#dfn-script-event-type]]]
        {field} (optional) Script Event Description [[[#dfn-script-event-description]]]
        {field} (optional) On Screen [[[#on-screen]]]
    }

    Class Text as "**Text**" [[#text]] {
        Text content [[[#dfn-text]]]
        Text Language Source [[[#text-language-source]]]
        {field} (optional) Language
        ' {field} (optional) Inline Style Attributes
    }
}

Class Character as "**Character**" [[#character]] {
    Character Identifier [[[#dfn-character-identifier]]]
    Name [[[#dfn-character-name]]]
    {field} (optional) Talent Name [[[#dfn-character-talent-name]]]
}

Class Style as "**Style**" {
    Style Identifier
    {field} (optional) Character Identifier [[[#dfn-character-identifier]]]
    Style Attributes
}

DAPTScript *-down- "0..*" ScriptEvent : contains
DAPTScript *-right- "0..*" Character : contains
DAPTScript *-right- "0..*" Style : contains
Character "0..1" <.down. "0..*" Style [[#dfn-character-style]] : Character Style
ScriptEvent "0..*" .right.> "0..*" Style [[#dfn-character-style]] : Character Style
Text "0..*" .right.> "0..*" Style [[#dfn-character-style]] : Character Style
Text "0..*" .right.> "0..*" Style : Other Style
ScriptEvent *-down- "0..*" Text : contains
ScriptEvent "0..*" ..> "0..*" Character

' Hidden links to persuade the layout to look nicer
DAPTScript -[hidden]r- Style
' Text -[hidden]d- Style

hide empty members
hide circle
@enduml