@startuml class-diagram
!theme plain
!pragma ratio 1.3
skinparam groupInheritance 2
skinparam linetype ortho
skinparam DefaultFontName sans-serif
skinparam DefaultFontSize 16
skinparam ArrowFontSize 13
skinparam ArrowMessageAlignment direction
skinparam Padding 4
' skinparam Nodesep 30
skinparam Ranksep 5
skinparam MinClassWidth 220

' scale 1024 width

together {

    Class DAPTScript as "**DAPT Script**" [[#dapt-script]] {
        Workflow Type [[[#workflow-type]]]
        Script Type [[[#script-type]]]
        Primary Language [[[#primary-language]]]
    }

    together {
        Class ScriptEvent as "**Script Event**" [[#script-event]] {
            Script Event Identifier [[[#dfn-script-event-identifier]]]
            {field} {abstract} (optional) Begin [[[#dfn-begin]]]
            {field} {abstract} (optional) End [[[#dfn-end]]]
            {field} {abstract} (optional) Duration [[[#dfn-duration]]]
            {field} (optional) Script Event Type [[[#dfn-script-event-type]]]
            {field} (optional) On Screen [[[#on-screen]]]
        }

        Class ScriptEventDescription as "**Script Event Description**" [[#dfn-script-event-description]] {
            {field} Description
            {field} (optional) Description Type [[[#dfn-description-type]]]
        }
    }

    Class Text as "**Text**" [[#text]] {
        Text content [[[#dfn-text]]]
        Text Language Source [[[#text-language-source]]]
        {field} (optional) Language
        ' {field} (optional) Inline Style Attributes
    }

    Class Style as "**Style**" {
        Style Identifier
        {field} (optional) Character Identifier [[[#dfn-character-identifier]]]
        Style Attributes
    }
    
}

Class Character as "**Character**" [[#character]] {
    Character Identifier [[[#dfn-character-identifier]]]
    Name [[[#dfn-character-name]]]
    {field} (optional) Talent Name [[[#dfn-character-talent-name]]]
}

'together {
    abstract Class Audio as "**Audio**" [[#dfn-audio]] {
    }

    class MixingInstruction as "**Mixing Instruction**" [[#dfn-mixing-instruction]] {
        {field} (optional) Gain [[[#dfn-gain]]]
        {field} (optional) Pan [[[#dfn-pan]]]
        {field} {abstract} (optional) Begin [[[#dfn-begin]]]
        {field} {abstract} (optional) End [[[#dfn-end]]]
        {field} {abstract} (optional) Duration [[[#dfn-duration]]]
        {field} (optional) Fill [[[#dfn-fill]]]
    }

    Class SynthesizedAudio as "**Synthesized Audio**" [[#dfn-synthesized-audio]] {
        Rate [[[#dfn-rate]]]
        {field} (optional) Pitch [[[#dfn-pitch]]]
    }

    Class AudioRecording as "**Audio Recording**" [[#dfn-audio-recording]] {
        Source [ ] [[[#dfn-source]]]
        Type [ ] [[[#dfn-type]]]
        {field} {abstract} (optional) Begin [[[#dfn-begin]]]
        {field} {abstract} (optional) End [[[#dfn-end]]]
        {field} {abstract} (optional) Duration [[[#dfn-duration]]]
        {field} (optional) In Time [[[#dfn-in-time]]]
        {field} (optional) Out Time [[[#dfn-out-time]]]
    }

'}


' MixingInstruction -[hidden]r-AudioRecording


DAPTScript *-- "0..* " ScriptEvent : contains >
DAPTScript *-[norank]- "0..*" Character : contains\r >
DAPTScript *-[norank]- "0..*  " Style : contains >
Character "0..1  " <.down "0..*" Style [[#dfn-character-style]] : Character\rStyle
ScriptEvent *-- "0..*" Text : contains >
ScriptEvent "0..*" .[norank]> "0..*" Style [[#dfn-character-style]] : Character\rStyle
ScriptEvent *-left> "0..*" ScriptEventDescription : contains >
ScriptEvent *- "0..*" MixingInstruction : contains >
Text "0..*" .[norank].> "0..*" Style [[#dfn-character-style]] : Character\nStyle
Text "0..*" ..> "0..*" Style : Other\nStyle
Text *-- "0..* " Audio : contains >
Text *-- "0..* " MixingInstruction : contains >
ScriptEvent "0..*" ..left> "0..*" Character
AudioRecording *-right- "0..* " MixingInstruction : contains >
Audio <|-- SynthesizedAudio : is <
Audio <|-- AudioRecording : is <

SynthesizedAudio -[hidden]r- AudioRecording

' Hidden links to persuade the layout to look nicer
' DAPTScript -[hidden]right- Style
Text -[hidden]right--- Style
Character -[hidden]down Style
' ScriptEventDescription -[hidden]- MixingInstruction
' MixingInstruction -[hidden]left- Text
' Text -[hidden]left- Style
' AudioRecording -[hidden]right- SynthesizedAudio

hide empty members
hide circle
@enduml